# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20230430-121907-navy-stain

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: it


# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
pipeline:
- name: "SpacyNLP"
  # language model to load
  model: "it_core_news_md"

  # when retrieving word vectors, this will decide if the casing
  # of the word is relevant. E.g. `hello` and `Hello` will
  # retrieve the same vector, if set to `False`. For some
  # applications and models it makes sense to differentiate
  # between these two words, therefore setting this to `True`.
  case_sensitive: False
  stop_words:
      - "il"
      - "i"
      - "la"
      - "le"
      - "lo"
      - "gli"
      - "un"
      - "una"
      - "uno"
      - "dei"
      - "degli"
      - "delle"

#- name: "WhitespaceTokenizer"
#- name: "RegexFeaturizer"
#- name: "CRFEntityExtractor"

# TOKENIZATION
#separa le parole con gli spazi
- name: "SpacyTokenizer"
  # Flag to check whether to split intents
  "intent_tokenization_flag": false
  # Symbol on which intent should be split
  "intent_split_symbol": "_"
  # Regular expression to detect tokens
  "token_pattern": None


# FEATURIZATION 
# You need to decide whether to use components that provide pre-trained word embeddings or not. 
# We recommend in cases of small amounts of training data to start with pre-trained word embeddings.
# If you can't find a pre-trained model for your language, you should use supervised embeddings.
- name: "SpacyFeaturizer"
  # Specify what pooling operation should be used to calculate the vector of
  # the complete utterance. Available options: 'mean' and 'max'.
  "pooling": "mean"

#componente di elaborazione del linguaggio naturale utilizzato per estrarre informazioni specifiche dal testo utilizzando espressioni regolari, 
#al fine di addestrare modelli di apprendimento automatico per compiti come la classificazione del testo o l'estrazione di informazioni.
#- name: "RegexFeaturizer"
#componente NLP utilizzato per estrarre entità nominative da un testo utilizzando un modello basato su CRF
#- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"
# - name: CountVectorsFeaturizer
#   analyzer: char_wb
#   min_ngram: 1
#   max_ngram: 4

# DIETClassifier for intent classification and entity recognition
- name: DIETClassifier
  epochs: 150
  constrain_similarities: true

# Maps synonymous entity values to the same value.
- name: EntitySynonymMapper

# ResponseSelector for response selection.
- name: ResponseSelector
  epochs: 150
  constrain_similarities: true

# Although Rasa will generalize to unseen messages, some messages might receive a low classification confidence. 
# Using Fallbacks will help ensure that these low confidence messages are handled gracefully, 
# giving your assistant the option to either respond with a default message or attempt to disambiguate the user input.
- name: FallbackClassifier
  threshold: 0.7
 # ambiguity_threshold: 0.1




# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies: 
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: UnexpecTEDIntentPolicy
     max_history: 5
     epochs: 150
   - name: TEDPolicy
     max_history: 5
     epochs: 150
     constrain_similarities: true

  
